# Generated by Django 5.1.6 on 2025-02-13 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField()),
                ('color', models.CharField()),
                ('favorite_food', models.CharField()),
                ('favorite_toy', models.CharField()),
            ],
        ),
    ]
