# Generated by Django 5.1.6 on 2025-02-16 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('size', models.CharField()),
                ('friendliness', models.IntegerField()),
                ('trainability', models.IntegerField()),
                ('shedding_amount', models.IntegerField()),
                ('exercise_needs', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField()),
                ('color', models.CharField()),
                ('favorite_food', models.CharField()),
                ('favorite_toy', models.CharField()),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogapi.breed')),
            ],
        ),
    ]
