# Generated by Django 5.1.6 on 2025-02-16 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogapi', '0002_alter_breed_exercise_needs_alter_breed_friendliness_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dogs', to='dogapi.breed'),
        ),
    ]
